# Generated by Django 5.2.6 on 2025-09-10 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Drug name', max_length=200)),
                ('manufacturer', models.CharField(help_text='Manufacturer name', max_length=200)),
                ('batch_number', models.CharField(help_text='Unique batch number', max_length=100, unique=True)),
                ('manufacture_date', models.DateField(help_text='Date of manufacture')),
                ('expiry_date', models.DateField(help_text='Expiry date')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in stock')),
                ('qr_code', models.ImageField(blank=True, help_text='Auto-generated QR code', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug Batch',
                'verbose_name_plural': 'Drug Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
